name = "OceananigansLagrangianFilter"
uuid = "3a2ee588-b56c-4451-ba19-103f511bcf00"
authors = ["lbaker "]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
