[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
OceananigansLagrangianFilter = "3a2ee588-b56c-4451-ba19-103f511bcf00"
